# Generated by Django 5.1.6 on 2025-02-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartrate',
            old_name='bpm',
            new_name='heart_rate',
        ),
    ]
