# Generated by Django 5.1.6 on 2025-02-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_bpm_heartrate_heart_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='heart_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rates', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
